# Generated by Django 4.1.1 on 2022-09-18 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='work',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 17, 48, 13, 10417, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
