# Generated by Django 4.1.1 on 2022-09-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_work_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='pub_date',
        ),
    ]
