# Generated by Django 4.1.1 on 2022-09-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_work_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
