# Generated by Django 4.1.1 on 2022-09-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_work_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='estimate',
            field=models.IntegerField(default=60),
        ),
    ]
