# Generated by Django 2.2.12 on 2022-10-14 22:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20221014_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobassignments',
            name='user',
        ),
        migrations.AddField(
            model_name='jobassignments',
            name='cuser',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.customUser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobassignments',
            name='work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.work'),
        ),
        migrations.AlterField(
            model_name='work',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 14, 22, 34, 36, 569316), verbose_name='date published'),
        ),
    ]
