# Generated by Django 2.2.12 on 2022-10-14 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20221014_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 14, 22, 40, 12, 90646), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='jobAssignments',
        ),
    ]
