# Generated by Django 2.2.12 on 2022-10-15 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20221014_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 15, 11, 29, 41, 15098), verbose_name='date published'),
        ),
    ]
