# Generated by Django 4.1.1 on 2022-10-15 22:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0027_alter_work_pub_date_jobassignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobassignments',
            name='employee',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 15, 22, 22, 58, 292434), verbose_name='date published'),
        ),
    ]
