# Generated by Django 4.1.1 on 2022-10-15 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_jobassignments_employee_alter_work_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 15, 22, 55, 2, 148954), verbose_name='date published'),
        ),
    ]
